# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hivemind < Formula
  desc "Hivemind - A TUI-based agent-driven IDE for managing multiple AI agents"
  homepage "https://github.com/ByteMirror/hivemind"
  version "0.2.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.0/hivemind_0.2.0_darwin_amd64.tar.gz"
      sha256 "c8c89c3e477294d1af5901b5af8033f036f4ddf2647c895bb168e6bea35215c5"

      def install
        bin.install "hivemind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.0/hivemind_0.2.0_darwin_arm64.tar.gz"
      sha256 "b56c249d20364ed4f58a0ac579d03bb81106e3074e4392a0d4c934177a1f0c0c"

      def install
        bin.install "hivemind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.0/hivemind_0.2.0_linux_amd64.tar.gz"
      sha256 "b685556df2dee48c73ae9e6eeebfa78802184bf508a05897ae51092fa3aee86c"
      def install
        bin.install "hivemind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.0/hivemind_0.2.0_linux_arm64.tar.gz"
      sha256 "cb080270813518e368b7a5b6386e0552e7d908a7a58094e9aad6d40467196293"
      def install
        bin.install "hivemind"
      end
    end
  end

  test do
    system "#{bin}/hivemind", "version"
  end
end
