# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hivemind < Formula
  desc "Hivemind - A TUI-based agent-driven IDE for managing multiple AI agents"
  homepage "https://github.com/ByteMirror/hivemind"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.1.0/hivemind_0.1.0_darwin_amd64.tar.gz"
      sha256 "25185b58571332b4f5bdc0c3cb2afa35b3bb75078a81d960f068d8cc6cafab69"

      def install
        bin.install "hivemind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.1.0/hivemind_0.1.0_darwin_arm64.tar.gz"
      sha256 "374b9ceff7a0e7396a4787115daef25a651ac9923e61e9923bffa8a565fa3e02"

      def install
        bin.install "hivemind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.1.0/hivemind_0.1.0_linux_amd64.tar.gz"
      sha256 "eb38bd72dc6db813a06f27e61fe9e12ee82d704978206418d6abec948eda623f"
      def install
        bin.install "hivemind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.1.0/hivemind_0.1.0_linux_arm64.tar.gz"
      sha256 "1e3e83bad81f0edd22df6e6737b1c19bdcefa959491fdef1eb490e566d828166"
      def install
        bin.install "hivemind"
      end
    end
  end

  test do
    system "#{bin}/hivemind", "version"
  end
end
