# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hivemind < Formula
  desc "Hivemind - A TUI-based agent-driven IDE for managing multiple AI agents"
  homepage "https://github.com/ByteMirror/hivemind"
  version "0.2.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.1/hivemind_0.2.1_darwin_amd64.tar.gz"
      sha256 "03a760c80e08efdba661441574900ac25ec94c93b4dc3e68f17199d716cc8932"

      define_method(:install) do
        bin.install "hivemind"
        bin.install "hivemind-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.1/hivemind_0.2.1_darwin_arm64.tar.gz"
      sha256 "4f9ae2ddc63fac1d9f2d8fccd97798dadb591a4ac470791152c60a047a229212"

      define_method(:install) do
        bin.install "hivemind"
        bin.install "hivemind-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.1/hivemind_0.2.1_linux_amd64.tar.gz"
      sha256 "11fe246e5ac66721469a4ed7103063af725cc04c3848c2bead02e29647228fe6"
      define_method(:install) do
        bin.install "hivemind"
        bin.install "hivemind-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ByteMirror/hivemind/releases/download/v0.2.1/hivemind_0.2.1_linux_arm64.tar.gz"
      sha256 "88daf6e951b2ab6a20ffeafba4a2177fe7528eeb64d5ac134dafbeccbc905703"
      define_method(:install) do
        bin.install "hivemind"
        bin.install "hivemind-mcp"
      end
    end
  end

  test do
    system "#{bin}/hivemind", "version"
  end
end
